[workspace]
members = [
    "crates/dap-core",
    "crates/dap-cli",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
regex = "1.12"
atty = "0.2"
tempfile = "3.23"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
