[package]
name = "riveroftime"
version = "0.1.0"
edition = "2021"

[dependencies]
smithay-client-toolkit = { version = "0.19", default-features = false, features = ["calloop"] }
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.2", features = ["client"] }
calloop = "0.13"
calloop-wayland-source = "0.3"
rusttype = "0.9"
log = "0.4.29"
env_logger = "0.11.8"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
clap = { version = "4.5.54", features = ["derive"] }
directories = "6.0.0"
thiserror = "2.0.18"
chrono = "0.4.43"
ratatui = "0.30.0"
crossterm = "0.29.0"
regex = "1.12.2"
anyhow = "1.0.100"
shellexpand = "3.1.1"

[dev-dependencies]
tempfile = "3.24.0"
